//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExperience
    {
        public int ExpId { get; set; }
        public string ExpTitle { get; set; }
        public string ExpSubTitle { get; set; }
        public string ExpDescription { get; set; }
        public string ExpDate { get; set; }
    }
}
