//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEducation
    {
        public int EducationId { get; set; }
        public string EducationName { get; set; }
        public string EducationDate { get; set; }
        public string EducationImgUrl { get; set; }
        public string EducationSubName { get; set; }
    }
}
