//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSocialMedia
    {
        public int SocialMediaId { get; set; }
        public string SocialMediaUrl { get; set; }
        public string Name { get; set; }
        public string SocialMediaImgUrl { get; set; }
    }
}
